"""Initial Migration

Revision ID: 306679134a57
Revises: 62e534197a9f
Create Date: 2020-11-04 13:19:37.932571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306679134a57'
down_revision = '62e534197a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
